<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$anomin = date('Y') - 18 . date('md');
$anovei = date('Y') + 2;
$anorena = date('Y') + 1;

$config = array(
    'cotacao' => array(
        array('field' => 'idParceiro', 'label' => 'idParceiro', 'rules' => 'trim|required|max_length[10]|integer'),
        array('field' => 'nmParceiro', 'label' => 'nomeParceiro', 'rules' => 'trim|required|max_length[50]'),
        array('field' => 'indProprietVeic', 'label' => 'indProprietVeic', 'rules' => 'trim|required|max_length[1]|less_than[2]'),
        array('field' => 'indCondutorVeic', 'label' => 'indCondutorVeic', 'rules' => 'trim|required|max_length[1]|less_than[2]'),
        array('field' => 'comissao', 'label' => 'comissao', 'rules' => 'trim|required|integer|max_length[2]'),
    ),
    'veiculoCotacao' => array(
        array('field' => 'veiCodFipe', 'label' => 'veiCodFipe', 'rules' => 'trim|required|max_length[10]'),
        array('field' => 'veiAno', 'label' => 'veiAno', 'rules' => "trim|required|integer|min_length[4]|max_length[4]|less_than[{$anovei}]"),
        array('field' => 'veiAnoFab', 'label' => 'veiAnoFab', 'rules' => "trim|integer|min_length[4]|max_length[4]|less_than[{$anovei}]"),
        array('field' => 'veiIndZero', 'label' => 'veiIndZero', 'rules' => 'trim|required|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiCdUtiliz', 'label' => 'veiCdUtiliz', 'rules' => 'trim|required|integer|max_length[1]|greater_than[0]|less_than[3]'),
        array('field' => 'veiCdTipo', 'label' => 'veiCdTipo', 'rules' => 'trim|required|integer|max_length[5]'),
        array('field' => 'veiCdCombust', 'label' => 'veiCdCombust', 'rules' => 'trim|required|integer'),
        array('field' => 'veiPlaca', 'label' => 'veiPlaca', 'rules' => 'trim|max_length[7]|min_length[7]|alpha_numeric'),
        array('field' => 'veiMunPlaca', 'label' => 'veiMunPlaca', 'rules' => 'trim|max_length[100]'),
        array('field' => 'veiCor', 'label' => 'veiCor', 'rules' => 'trim|max_length[50]'),
        array('field' => 'veiCdUfPlaca', 'label' => 'veiCdUfPlaca', 'rules' => 'trim|integer|max_length[3]'),
        array('field' => 'veiRenav', 'label' => 'veiRenav', 'rules' => 'trim|max_length[11]|numeric|min_length[11]|max_length[11]'),
        array('field' => 'veiAnoRenav', 'label' => 'veiAnoRenav', 'rules' => "trim|integer|min_length[4]|max_length[4]|less_than[{$anorena}]"),
        array('field' => 'veiChassi', 'label' => 'veiChassi', 'rules' => 'trim|min_length[17]|max_length[17]|alpha_numeric'),
        array('field' => 'veiIndChassiRema', 'label' => 'veiIndChassiRema', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiIndLeilao', 'label' => 'veiIndLeilao', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiIndAcidentado', 'label' => 'veiIndAcidentado', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiIndAlienado', 'label' => 'veiIndAlienado', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
    ),
    'seguradoCotacao' => array(
        array('field' => 'segNomeRazao', 'label' => 'segNomeRazao', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segCpfCnpj', 'label' => 'segCpfCnpj', 'rules' => 'trim|min_length[11]|max_length[14]|numeric'),
        array('field' => 'segDtNasci', 'label' => 'segDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'segCdSexo', 'label' => 'segCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'segCdEstCivl', 'label' => 'segCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'segProfRamoAtivi', 'label' => 'segProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
        array('field' => 'segEmail', 'label' => 'segEmail', 'rules' => 'trim|valid_email|required'),
        array('field' => 'segCelDdd', 'label' => 'segCelDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'segCelNum', 'label' => 'segCelNum', 'rules' => 'trim|max_length[9]|min_length[8]|integer|greater_than[40000000]'),
        array('field' => 'segFoneDdd', 'label' => 'segFoneDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'segFoneNum', 'label' => 'segFoneNum', 'rules' => 'trim|max_length[8]|integer'),
        array('field' => 'segEnd', 'label' => 'segEnd', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segEndNum', 'label' => 'segEndNum', 'rules' => 'trim|max_length[10]'),
        array('field' => 'segEndCompl', 'label' => 'segEndCompl', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segEndCep', 'label' => 'segEndCep', 'rules' => 'trim|max_length[8]|min_length[8]|numeric'),
        array('field' => 'segEndCidade', 'label' => 'segEndCidade', 'rules' => 'trim|max_length[100]'),
        array('field' => 'segEndCdUf', 'label' => 'segEndCdUf', 'rules' => 'trim|integer|max_length[5]'),
    ),
    'seguradoCotacaoPJ' => array(
        array('field' => 'segNomeRazao', 'label' => 'segNomeRazao', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segCpfCnpj', 'label' => 'segCpfCnpj', 'rules' => 'trim|min_length[11]|max_length[14]|numeric'),
        array('field' => 'segDtNasci', 'label' => 'segDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[18000000]'),
        array('field' => 'segCdSexo', 'label' => 'segCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'segCdEstCivl', 'label' => 'segCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'segProfRamoAtivi', 'label' => 'segProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
        array('field' => 'segEmail', 'label' => 'segEmail', 'rules' => 'trim|valid_email|required'),
        array('field' => 'segCelDdd', 'label' => 'segCelDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'segCelNum', 'label' => 'segCelNum', 'rules' => 'trim|max_length[9]|min_length[8]|integer|greater_than[40000000]'),
        array('field' => 'segFoneDdd', 'label' => 'segFoneDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'segFoneNum', 'label' => 'segFoneNum', 'rules' => 'trim|max_length[8]|integer'),
        array('field' => 'segEnd', 'label' => 'segEnd', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segEndNum', 'label' => 'segEndNum', 'rules' => 'trim|max_length[10]'),
        array('field' => 'segEndCompl', 'label' => 'segEndCompl', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segEndCep', 'label' => 'segEndCep', 'rules' => 'trim|max_length[8]|min_length[8]|numeric'),
        array('field' => 'segEndCidade', 'label' => 'segEndCidade', 'rules' => 'trim|max_length[100]'),
        array('field' => 'segEndCdUf', 'label' => 'segEndCdUf', 'rules' => 'trim|integer|max_length[5]'),
    ),
    'corretor' => array(
        array('field' => 'correCodPlataforma', 'label' => 'correCodPlataforma', 'rules' => 'trim|max_length[20]|integer'),
        array('field' => 'correSusep', 'label' => 'correSusep', 'rules' => 'trim|max_length[20]|numeric'),
        array('field' => 'correNomeRazao', 'label' => 'correNomeRazao', 'rules' => 'trim|required|max_length[50]'),
        array('field' => 'correCpfCnpj', 'label' => 'correCpfCnpj', 'rules' => 'trim|required|min_length[11]|max_length[14]|numeric'),
        array('field' => 'correDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'correCdSexo', 'label' => 'correCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'correCdEstCivl', 'label' => 'correCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'correProfRamoAtivi', 'label' => 'correProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
        array('field' => 'correEmail', 'label' => 'correEmail', 'rules' => 'trim|required|valid_email'),
        array('field' => 'correCelDdd', 'label' => 'correCelDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'correCelNum', 'label' => 'correCelNum', 'rules' => 'trim|max_length[9]|min_length[8]|integer|greater_than[40000000]'),
        array('field' => 'correFoneDdd', 'label' => 'correFoneDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'correFoneNum', 'label' => 'correFoneNum', 'rules' => 'trim|max_length[8]|integer'),
        array('field' => 'correEndNum', 'label' => 'correEndNum', 'rules' => 'trim|max_length[10]'),
        array('field' => 'correEndCompl', 'label' => 'correEndCompl', 'rules' => 'trim|max_length[50]'),
        array('field' => 'correEndCep', 'label' => 'correEndCep', 'rules' => 'trim|max_length[8]|min_length[8]|numeric'),
        array('field' => 'correEndCidade', 'label' => 'correEndCidade', 'rules' => 'trim|max_length[20]'),
        array('field' => 'correEndCdUf', 'label' => 'correEndCdUf', 'rules' => 'trim|integer|max_length[5]'),
    ),
    'condutorCotacao' => array(
        array('field' => 'condutNomeRazao', 'label' => 'condutNomeRazao', 'rules' => 'trim|max_length[50]'),
        array('field' => 'condutCpfCnpj', 'label' => 'condutCpfCnpj', 'rules' => 'trim|min_length[11]|max_length[11]|numeric'),
        array('field' => 'condutDtNasci', 'label' => 'condutDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'condutCdSexo', 'label' => 'condutCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'condutCdEstCivl', 'label' => 'condutCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'condutProfRamoAtivi', 'label' => 'condutProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
    ),
    'proprietarioCotacao' => array(
        array('field' => 'proprNomeRazao', 'label' => 'proprNomeRazao', 'rules' => 'trim|max_length[50]'),
        array('field' => 'proprCpfCnpj', 'label' => 'proprCpfCnpj', 'rules' => 'trim|min_length[11]|max_length[14]|numeric'),
        array('field' => 'proprDtNasci', 'label' => 'proprDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'proprCdSexo', 'label' => 'proprCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'proprCdEstCivl', 'label' => 'proprCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'proprPrfoRamoAtivi', 'label' => 'proprProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
        array('field' => 'proprEmail', 'label' => 'proprEmail', 'rules' => 'trim|valid_email'),
        array('field' => 'proprCelDdd', 'label' => 'proprCelDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'proprCelNum', 'label' => 'proprCelNum', 'rules' => 'trim|max_length[9]|min_length[8]|integer|greater_than[40000000]'),
        array('field' => 'proprFoneDdd', 'label' => 'proprFoneDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'proprFoneNum', 'label' => 'proprFoneNum', 'rules' => 'trim|max_length[8]|integer'),
        array('field' => 'proprEndNum', 'label' => 'proprEndNum', 'rules' => 'trim|max_length[10]'),
        array('field' => 'proprEndCompl', 'label' => 'proprEndCompl', 'rules' => 'trim|max_length[50]'),
        array('field' => 'proprEndCep', 'label' => 'proprEndCep', 'rules' => 'trim|max_length[8]|numeric'),
        array('field' => 'proprEndCidade', 'label' => 'proprEndCidade', 'rules' => 'trim|max_length[20]'),
        array('field' => 'proprEndCdUf', 'label' => 'proprEndCdUf', 'rules' => 'trim|integer|max_length[5]'),
    ),
    /*
     * PORPOSTA VALIDAÇÃO
     */
    'proposta' => array(
        array('field' => 'idParceiro', 'label' => 'idParceiro', 'rules' => 'trim|required|max_length[10]|integer'),
        array('field' => 'nmParceiro', 'label' => 'nomeParceiro', 'rules' => 'trim|required|max_length[50]'),
        array('field' => 'indProprietVeic', 'label' => 'indProprietVeic', 'rules' => 'trim|required|max_length[1]'),
        array('field' => 'indCondutorVeic', 'label' => 'indCondutorVeic', 'rules' => 'trim|required|max_length[1]'),
        array('field' => 'cdCotacao', 'label' => 'cdCotacao', 'rules' => 'trim|required|integer|max_length[50]'),
        array('field' => 'qtParcela', 'label' => 'qtParcela', 'rules' => 'trim|required|integer|max_length[3]'),
        array('field' => 'cdFormaPgt', 'label' => 'cdFormaPgt', 'rules' => 'trim|required|numeric|max_length[2]'),
        array('field' => 'nmBandeira', 'label' => 'Bandeira do Cartão', 'rules' => 'trim|max_length[60]'),
        array('field' => 'validadeCartao', 'label' => 'Validade do Cartão', 'rules' => 'trim|numeric|max_length[6]|greater_than['.date("Ym",strtotime("-1 month")).']'),
        array('field' => 'numCartao', 'label' => 'Numero do Cartão', 'rules' => 'trim|numeric|max_length[16]|min_length[16]'),
    ),
    'veiculoProposta' => array(
        array('field' => 'veiCodFipe', 'label' => 'veiCodFipe', 'rules' => 'trim|required|max_length[10]'),
        array('field' => 'veiAno', 'label' => 'veiAno', 'rules' => "trim|required|integer|min_length[4]|max_length[4]|less_than[{$anovei}]"),
        array('field' => 'veiAnoFab', 'label' => 'veiAnoFab', 'rules' => "trim|integer|min_length[4]|max_length[4]|less_than[{$anovei}]"),
        array('field' => 'veiIndZero', 'label' => 'veiIndZero', 'rules' => 'trim|required|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiCdUtiliz', 'label' => 'veiCdUtiliz', 'rules' => 'trim|required|integer|max_length[1]|greater_than[0]|less_than[3]'),
        array('field' => 'veiCdTipo', 'label' => 'veiCdTipo', 'rules' => 'trim|required|integer|max_length[5]'),
        array('field' => 'veiCdCombust', 'label' => 'veiCdCombust', 'rules' => 'trim|required|integer'),
        array('field' => 'veiPlaca', 'label' => 'veiPlaca', 'rules' => 'trim|required|max_length[7]|min_length[7]|alpha_numeric'),
        array('field' => 'veiCor', 'label' => 'veiCor', 'rules' => 'trim|max_length[50]'),
        array('field' => 'veiMunPlaca', 'label' => 'veiMunPlaca', 'rules' => 'trim|max_length[50]'),
        array('field' => 'veiCdUfPlaca', 'label' => 'veiCdUfPlaca', 'rules' => 'trim|required|integer|max_length[3]'),
        array('field' => 'veiRenav', 'label' => 'veiRenav', 'rules' => 'trim|required|max_length[11]|numeric|min_length[11]'),
        array('field' => 'veiAnoRenav', 'label' => 'veiAnoRenav', 'rules' => "trim|integer|min_length[4]|max_length[4]|less_than[{$anorena}]"),
        array('field' => 'veiChassi', 'label' => 'veiChassi', 'rules' => 'trim|required|min_length[17]|max_length[17]|alpha_numeric'),
        array('field' => 'veiIndChassiRema', 'label' => 'veiIndChassiRema', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiIndLeilao', 'label' => 'veiIndLeilao', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiIndAcidentado', 'label' => 'veiIndAcidentado', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
        array('field' => 'veiIndAlienado', 'label' => 'veiIndAlienado', 'rules' => 'trim|integer|max_length[1]|less_than[2]'),
    ),
    'seguradoProposta' => array(
        array('field' => 'segNomeRazao', 'label' => 'segNomeRazao', 'rules' => 'trim|required|max_length[50]'),
        array('field' => 'segCpfCnpj', 'label' => 'segCpfCnpj', 'rules' => 'trim|required|min_length[11]|max_length[14]|numeric'),
        array('field' => 'segDtNasci', 'label' => 'segDtNasci', 'rules' => 'trim|required|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'segCdSexo', 'label' => 'segCdSexo', 'rules' => 'trim|required|max_length[1]|numeric|less_than[3]'),
        array('field' => 'segCdEstCivl', 'label' => 'segCdEstCivl', 'rules' => 'trim|required|max_length[3]|integer'),
        array('field' => 'segProfRamoAtivi', 'label' => 'segProfRamoAtivi', 'rules' => 'trim|required|max_length[10]|integer'),
        array('field' => 'segEmail', 'label' => 'segEmail', 'rules' => 'trim|required|valid_email|required'),
        array('field' => 'segCelDdd', 'label' => 'segCelDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'segCelNum', 'label' => 'segCelNum', 'rules' => 'trim|max_length[9]|min_length[8]|integer|greater_than[40000000]'),
        array('field' => 'segFoneDdd', 'label' => 'segFoneDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'segFoneNum', 'label' => 'segFoneNum', 'rules' => 'trim|max_length[8]|integer'),
        array('field' => 'segEnd', 'label' => 'segEnd', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segEndNum', 'label' => 'segEndNum', 'rules' => 'trim|required|max_length[10]'),
        array('field' => 'segEndCompl', 'label' => 'segEndCompl', 'rules' => 'trim|max_length[50]'),
        array('field' => 'segEndCep', 'label' => 'segEndCep', 'rules' => 'trim|required|max_length[8]|min_length[8]|numeric'),
        array('field' => 'segEndCidade', 'label' => 'segEndCidade', 'rules' => 'trim|required|max_length[20]'),
        array('field' => 'segEndCdUf', 'label' => 'segEndCdUf', 'rules' => 'trim|integer|required|max_length[5]'),
    ),
    'condutorProposta' => array(
        array('field' => 'condutNomeRazao', 'label' => 'condutNomeRazao', 'rules' => 'trim|max_length[50]'),
        array('field' => 'condutCpfCnpj', 'label' => 'condutCpfCnpj', 'rules' => 'trim|min_length[11]|max_length[11]|numeric'),
        array('field' => 'condutDtNasci', 'label' => 'condutDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'condutCdSexo', 'label' => 'condutCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'condutCdEstCivl', 'label' => 'condutCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'condutProfRamoAtivi', 'label' => 'condutProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
    ),
    'proprietarioProposta' => array(
        array('field' => 'proprNomeRazao', 'label' => 'proprNomeRazao', 'rules' => 'trim|max_length[50]'),
        array('field' => 'proprCpfCnpj', 'label' => 'proprCpfCnpj', 'rules' => 'trim|min_length[11]|max_length[14]|numeric'),
        array('field' => 'proprDtNasci', 'label' => 'proprDtNasci', 'rules' => 'trim|max_length[8]|min_length[8]|integer|greater_than[19000000]|less_than[' . $anomin . ']'),
        array('field' => 'proprCdSexo', 'label' => 'proprCdSexo', 'rules' => 'trim|max_length[1]|numeric|less_than[3]'),
        array('field' => 'proprCdEstCivl', 'label' => 'proprCdEstCivl', 'rules' => 'trim|max_length[3]|integer'),
        array('field' => 'proprPrfoRamoAtivi', 'label' => 'proprProfRamoAtivi', 'rules' => 'trim|max_length[10]|integer'),
        array('field' => 'proprEmail', 'label' => 'proprEmail', 'rules' => 'trim|valid_email'),
        array('field' => 'proprCelDdd', 'label' => 'proprCelDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'proprCelNum', 'label' => 'proprCelNum', 'rules' => 'trim|max_length[9]|min_length[8]|integer|greater_than[40000000]'),
        array('field' => 'proprFoneDdd', 'label' => 'proprFoneDdd', 'rules' => 'trim|max_length[2]|integer|greater_than[10]|less_than[100]'),
        array('field' => 'proprFoneNum', 'label' => 'proprFoneNum', 'rules' => 'trim|max_length[8]|integer'),
        array('field' => 'proprEndNum', 'label' => 'proprEndNum', 'rules' => 'trim|max_length[10]'),
        array('field' => 'proprEndCompl', 'label' => 'proprEndCompl', 'rules' => 'trim|max_length[50]'),
        array('field' => 'proprEndCep', 'label' => 'proprEndCep', 'rules' => 'trim|max_length[8]|numeric'),
        array('field' => 'proprEndCidade', 'label' => 'proprEndCidade', 'rules' => 'trim|max_length[20]'),
        array('field' => 'proprEndCdUf', 'label' => 'proprEndCdUf', 'rules' => 'trim|integer|max_length[5]'),
    ),
    'pdf' => array(
        array('field' => 'idParceiro', 'label' => 'idParceiro', 'rules' => 'trim|required|max_length[10]|integer'),
        array('field' => 'nmParceiro', 'label' => 'nomeParceiro', 'rules' => 'trim|required|max_length[50]'),
        array('field' => 'idProposta', 'label' => 'idProposta', 'rules' => 'trim|required|integer'),
    ),
);


